name: Publish Bicep modules

on:
  workflow_dispatch:
  push:
    branches:
      - main


permissions:
  id-token: write
  contents: write
  pull-requests: write

jobs:
  publish-release:
    runs-on: ubuntu-latest
    environment: prd
    steps:
    - name: Publish
      env:
        GITHUB_TOKEN: "${{ secrets.RELEASE_REPO_SECRET }}"
      run: |
        gh release create v0.0.1 -R https://github.com/foulonc/github-finder